version: '0.1'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'GradingSystem'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
  app:
    build: .
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: 'GradingSystem'
      DB_USER: 'user'
      DB_PASSWORD: '123456'
    ports:
      - "8080:8080"
volumes:
  my-db:
