Port: "8080"

Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

MySQL:
  IP: "mysql"
  Port: "3306"
  User: "root"
  Password: "123456"
  Database: "GradingSystem"

Redis:
  IP: "redis"
  Port: "6379"

SMTP:
  Host: "smtp.qq.com"
  Port: 465
  User: "1930551858@qq.com"
  Password: "kporpomwkyabdeda"